name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check disk space
        run: df -h

      - name: Remove extra software
        run: |
          sudo apt-get purge -y gfortran-9 gfortran-10
          sudo apt-get purge -y clang-10 lldb-10 lld-10
          sudo apt-get purge -y clang-12 lldb-12 lld-12
          sudo apt-get purge -y firefox
          sudo rm -rf /usr/local/share/chromium
          sudo apt-get purge -y mongodb-org
          sudo rm -rf /usr/share/swift
          sudo apt-get purge -y moby-engine moby-cli moby-buildx moby-compose
          sudo apt-get purge -y podman buildah skopeo
          sudo apt-get purge -y esl-erlang
          sudo rm -rf /usr/local/bin/rebar3
          sudo rm -rf /usr/local/bin/phantomjs
          sudo rm -rf /usr/local/bin/aliyun
          sudo apt-get purge -y ansible
          sudo rm -rf /usr/local/bin/aws
          sudo rm -rf /usr/local/bin/azcopy
          sudo rm -rf /usr/local/bin/bicep
          sudo apt-get purge -y google-cloud-sdk
          sudo apt-get purge -y hhvm
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /usr/lib/jvm
          sudo apt-get purge -y ant ant-optional
          sudo rm -rf /usr/share/gradle
          sudo rm -rf /usr/local/julia*
          sudo rm -rf /usr/share/kotlinc
          sudo rm -rf /usr/local/bin/kind
          sudo rm -rf /usr/local/bin/kubectl
          sudo rm -rf /usr/local/bin/lein
          sudo apt-get purge -y mercurial
          sudo apt-get purge -y mono-complete nuget
          sudo apt-add-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install php7.4-cgi

      - name: Check disk space
        run: df -h

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: actions/checkout@v2

      - name: Fetch depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Fetch Chromium source
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          mkdir chromium
          cd chromium
          fetch --nohooks --no-history chromium

      - name: Check disk space
        run: df -h

      - name: Install build deps
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          ./build/install-build-deps.sh

      - name: Check disk space
        run: df -h

      - name: gclient runhooks
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          gclient runhooks

      - name: Generate default config
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          gn gen out/Default

      - name: Build
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          autoninja -C out/Default chrome

      - uses: actions/upload-artifact@v2
        with:
          name: out/Default
          path: chromium/src/out/Default

